export const mockJobs = [
  {
    id: 1001,
    title: "Senior Frontend Engineer",
    company_name: "Fieldstone Labs",
    company_logo: "",
    category: "Software Development",
    job_type: "full_time",
    candidate_required_location: "USA",
    salary: "$120,000 - $150,000",
    publication_date: "2026-07-10T00:00:00",
    url: "#",
    description: "Build and maintain customer-facing React applications. Work closely with design and backend teams to ship features fast without sacrificing quality. 4+ years of React experience required."
  },
  {
    id: 1002,
    title: "Backend Engineer, Node.js",
    company_name: "Hollow Rock Systems",
    company_logo: "",
    category: "Software Development",
    job_type: "full_time",
    candidate_required_location: "Worldwide",
    salary: "$110,000 - $140,000",
    publication_date: "2026-07-08T00:00:00",
    url: "#",
    description: "Design and scale our Node.js/Postgres backend services. Own API design, database schema, and deployment pipelines for a growing logistics platform."
  },
  {
    id: 1003,
    title: "Product Designer",
    company_name: "Fieldstone Labs",
    company_logo: "",
    category: "Design",
    job_type: "contract",
    candidate_required_location: "Europe",
    salary: "$70/hr",
    publication_date: "2026-07-05T00:00:00",
    url: "#",
    description: "Contract role designing web and mobile flows for a small but growing SaaS product. Portfolio required."
  },
  {
    id: 1004,
    title: "DevOps Engineer",
    company_name: "Cinder Point",
    company_logo: "",
    category: "DevOps / Sysadmin",
    job_type: "full_time",
    candidate_required_location: "USA",
    salary: "$130,000 - $160,000",
    publication_date: "2026-07-01T00:00:00",
    url: "#",
    description: "Manage CI/CD pipelines and cloud infrastructure across AWS. Experience with Terraform and Kubernetes strongly preferred."
  },
  {
    id: 1005,
    title: "Customer Support Specialist",
    company_name: "Hollow Rock Systems",
    company_logo: "",
    category: "Customer Support",
    job_type: "part_time",
    candidate_required_location: "Worldwide",
    salary: "$25/hr",
    publication_date: "2026-06-28T00:00:00",
    url: "#",
    description: "Help our customers resolve issues over email and chat. Flexible part-time hours, fully remote."
  },
  {
    id: 1006,
    title: "Marketing Manager",
    company_name: "Cinder Point",
    company_logo: "",
    category: "Marketing",
    job_type: "full_time",
    candidate_required_location: "USA",
    salary: "$90,000 - $110,000",
    publication_date: "2026-06-25T00:00:00",
    url: "#",
    description: "Own our content and demand-gen strategy. Manage a small team of contractors and report directly to the VP of Growth."
  },
  {
    id: 1007,
    title: "Data Analyst",
    company_name: "Fieldstone Labs",
    company_logo: "",
    category: "Data Analysis",
    job_type: "freelance",
    candidate_required_location: "Worldwide",
    salary: "$50/hr",
    publication_date: "2026-06-20T00:00:00",
    url: "#",
    description: "Analyze product usage data to inform roadmap decisions. SQL and dashboarding experience (Looker or similar) required."
  },
  {
    id: 1008,
    title: "QA Engineer",
    company_name: "Cinder Point",
    company_logo: "",
    category: "QA",
    job_type: "full_time",
    candidate_required_location: "Canada",
    salary: "$95,000 - $115,000",
    publication_date: "2026-06-15T00:00:00",
    url: "#",
    description: "Build automated test suites and own release quality across our web and mobile apps."
  }
]
